<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Controller for handling anggota_lab module
 * @author : Doni Setio Pambudi (donisp06@gmail.com)
 */
class Anggota_lab extends CI_Controller {

	/*
	 * constructor class
	 */
	public function __construct() {
		parent::__construct();

		//set module, enable for authentication
		//$this->auth->set_default_module('anggota_lab');
		//enable dibawah ini jika divalidasi semua
		//$this->auth->validate(TRUE);
		//enable dibawah ini jika divalidasi user telah login saja
		//$this->auth->validate(TRUE, TRUE);

		//load this page model
		$this->load->model('m_anggota_lab');

		//load foregin lang if exist
		$this->lang->load('module/pegawai');
		$this->lang->load('module/laboratorium_penelitian');

		//load lang, place this module after foreign lang, so module_ not overriden by foreign lang
		$this->lang->load('module/anggota_lab');
  	}

	/*
	 * method index controller anggota_lab
     * generated by Doni's Framework Generator
	 *
	 * this method act as module entry point
	 *
	 * @author: Doni Setio Pambudi
	 * @access: public
	 * @return: no return, view a page
	 */
	public function index(){
		//$this->auth->set_access('view');
		//$this->auth->validate(TRUE);

		//set informasi halaman
		$this->site_info->set_page_title($this->lang->line('module_title'), $this->lang->line('module_subtitle'));
		//set breadcrumb
		$this->site_info->add_breadcrumb($this->lang->line('module_title'));
		//add menu highlight
		$this->site_info->set_current_module('anggota_lab');

		//add masterpage script
		$this->asset_library->add_masterpage_script();
		//add page javascript
		$this->asset_library->add_js('js/pages/anggota_lab.js');

		$data = array();
		$this->load->model('m_pegawai');
		$data['pegawai'] = $this->m_pegawai->get(/*'peg_deleted = 0', 'peg_name asc'*/);
		$this->load->model('m_laboratorium_penelitian');
		$data['laboratorium_penelitian'] = $this->m_laboratorium_penelitian->get(/*'lab_deleted = 0', 'lab_name asc'*/);

		//load view
		$this->load->view('base/header');
		$this->load->view('anggota_lab/master', $data);
		$this->load->view('base/footer');
	}

	/*
	 * get_datamaster method
     * generated by Doni's Framework Generator
	 *
	 * this method handle get datamaster request from datatables
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return	json string
	 */
	public function get_datamaster(){
		//only ajax is allowed
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('view');
		//$this->auth->validate();

		$filter_cols = array('alb_pegawai' => /*uintval(*/$this->input->post('alb_pegawai')/*, TRUE)*/,'alb_laboratorium' => /*uintval(*/$this->input->post('alb_laboratorium')/*, TRUE)*/);
		//$add_where = '';
		//set default where query
		$where = build_masterpage_filter($filter_cols /*, $add_where */);

		//get data
		$this->m_anggota_lab->get_datatable($where);
	}

	/*
	 * detail method
     * generated by Doni's Framework Generator
	 *
	 * this method handle get data detail from one primary key
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string
	 */
	public function detail(){
		//only ajax is allowed
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('view');
		//$this->auth->validate();

		//search data with pk for default
		$search_data = $this->input->post('alb_id');
		//if no search data exist, response error
		if($search_data === NULL)
			ajax_response('error');

		//activate if search data is integer
		//$search_data = uintval($search_data);

		//get detail
		$detail = $this->m_anggota_lab->get_by_column($search_data);

		//output return value
		if($detail !== NULL) ajax_response('ok', '', $detail);
		else ajax_response('error');
	}

	/*
	 * add method
     * generated by Doni's Framework Generator
	 *
	 * this method handle add data submit from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function add(){
		//$this->auth->set_access('add');
		//$this->auth->validate();

		//call save method
		$this->save();
	}

	/*
	 * edit method
     * generated by Doni's Framework Generator
	 *
	 * this method handle edit data submit from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function edit(){
		//$this->auth->set_access('edit');
		//$this->auth->validate();

		//call save method
		$this->save();
	}

	/*
	 * save method
     * generated by Doni's Framework Generator
	 *
	 * private method handle add and edit method
	 *
	 * @author	Doni Setio Pambudi
	 * @access	private
	 * @return		json string result ok or error
	 */
	private function save(){
		if(!$this->input->is_ajax_request()) show_404();

		//validation
		$this->load->library('form_validation');
		$this->form_validation->set_rules('alb_id'           , 'lang:alb_id'           , 'integer');
		$this->form_validation->set_rules('alb_pegawai'      , 'lang:alb_pegawai'      , 'integer');
		$this->form_validation->set_rules('alb_laboratorium' , 'lang:alb_laboratorium' , 'integer');
		$this->form_validation->set_rules('alb_status_ketua' , 'lang:alb_status_ketua' , 'trim|max_length[1]');
		$this->form_validation->set_rules('alb_periode_aktif', 'lang:alb_periode_aktif', 'trim|max_length[255]');

		if ($this->form_validation->run())
		{
			// insert
			if($this->input->post('alb_id') == '')
			{
				$alb_id = $this->m_anggota_lab->insert(
					$this->input->post('alb_pegawai'),
					$this->input->post('alb_laboratorium'),
					$this->input->post('alb_status_ketua'),
					$this->input->post('alb_periode_aktif')
				);
				write_log('anggota_lab', 'insert', "PK = $alb_id");
				ajax_response();
			}
			// update
			else
			{
				$pk_id = $this->input->post('alb_id');
				//check if pk integer
				//$pk_id = uintval($pk_id);
				$this->m_anggota_lab->update(
					$pk_id,
					$this->input->post('alb_pegawai'),
					$this->input->post('alb_laboratorium'),
					$this->input->post('alb_status_ketua'),
					$this->input->post('alb_periode_aktif')
				);
				write_log('anggota_lab', 'update', "PK = $pk_id");
				ajax_response();
			}
		}
		else
		{ ajax_response('error', validation_errors()); }
	}

	/*
	 * delete method
     * generated by Doni's Framework Generator
	 *
	 * method handle delete from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function delete(){
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('delete');
		//$this->auth->validate();

		if($this->input->post('alb_id') === NULL) ajax_response();

		$all_deleted = array();
		foreach($this->input->post('alb_id') as $row){
			//$row = uintval($row);
			//permanent delete row, check MY_Model, you can set flag with ->update_single_column
			$this->m_anggota_lab->permanent_delete($row);

			//this is sample code if you cannot delete, but you must update status
			//$this->m_anggota_lab->update_single_column('alb_deleted', 1, $row);
			$all_deleted[] = $row;
		}
		write_log('anggota_lab', 'delete', 'PK = ' . implode(",", $all_deleted));

		ajax_response();
	}
}