<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Controller for handling fakultas module
 * @author : Doni Setio Pambudi (donisp06@gmail.com)
 */
class Fakultas extends CI_Controller {

	/*
	 * constructor class
	 */
	public function __construct() {
		parent::__construct();

		//set module, enable for authentication
		//$this->auth->set_default_module('fakultas');
		//enable dibawah ini jika divalidasi semua
		//$this->auth->validate(TRUE);
		//enable dibawah ini jika divalidasi user telah login saja
		//$this->auth->validate(TRUE, TRUE);

		//load this page model
		$this->load->model('m_fakultas');

		//load foregin lang if exist


		//load lang, place this module after foreign lang, so module_ not overriden by foreign lang
		$this->lang->load('module/fakultas');
  	}

	/*
	 * method index controller fakultas
     * generated by Doni's Framework Generator
	 *
	 * this method act as module entry point
	 *
	 * @author: Doni Setio Pambudi
	 * @access: public
	 * @return: no return, view a page
	 */
	public function index(){
		//$this->auth->set_access('view');
		//$this->auth->validate(TRUE);

		//set informasi halaman
		$this->site_info->set_page_title($this->lang->line('module_title'), $this->lang->line('module_subtitle'));
		//set breadcrumb
		$this->site_info->add_breadcrumb($this->lang->line('module_title'));
		//add menu highlight
		$this->site_info->set_current_module('fakultas');

		//add masterpage script
		$this->asset_library->add_masterpage_script();
		//add page javascript
		$this->asset_library->add_js('js/pages/fakultas.js');

		$data = array();


		//load view
		$this->load->view('base/header');
		$this->load->view('fakultas/master', $data);
		$this->load->view('base/footer');
	}

	/*
	 * get_datamaster method
     * generated by Doni's Framework Generator
	 *
	 * this method handle get datamaster request from datatables
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return	json string
	 */
	public function get_datamaster(){
		//only ajax is allowed
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('view');
		//$this->auth->validate();

		$filter_cols = array();
		//$add_where = '';
		//set default where query
		$where = build_masterpage_filter($filter_cols /*, $add_where */);

		//get data
		$this->m_fakultas->get_datatable($where);
	}

	/*
	 * detail method
     * generated by Doni's Framework Generator
	 *
	 * this method handle get data detail from one primary key
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string
	 */
	public function detail(){
		//only ajax is allowed
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('view');
		//$this->auth->validate();

		//search data with pk for default
		$search_data = $this->input->post('fak_id');
		//if no search data exist, response error
		if($search_data === NULL)
			ajax_response('error');

		//activate if search data is integer
		//$search_data = uintval($search_data);

		//get detail
		$detail = $this->m_fakultas->get_by_column($search_data);

		//output return value
		if($detail !== NULL) ajax_response('ok', '', $detail);
		else ajax_response('error');
	}

	/*
	 * add method
     * generated by Doni's Framework Generator
	 *
	 * this method handle add data submit from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function add(){
		//$this->auth->set_access('add');
		//$this->auth->validate();

		//call save method
		$this->save();
	}

	/*
	 * edit method
     * generated by Doni's Framework Generator
	 *
	 * this method handle edit data submit from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function edit(){
		//$this->auth->set_access('edit');
		//$this->auth->validate();

		//call save method
		$this->save();
	}

	/*
	 * save method
     * generated by Doni's Framework Generator
	 *
	 * private method handle add and edit method
	 *
	 * @author	Doni Setio Pambudi
	 * @access	private
	 * @return		json string result ok or error
	 */
	private function save(){
		if(!$this->input->is_ajax_request()) show_404();

		//validation
		$this->load->library('form_validation');
		$this->form_validation->set_rules('fak_id'                   , 'lang:fak_id'                   , 'trim|max_length[3]');
		$this->form_validation->set_rules('fak_perguruan_tinggi'     , 'lang:fak_perguruan_tinggi'     , 'trim|max_length[6]');
		$this->form_validation->set_rules('fak_status_validasi'      , 'lang:fak_status_validasi'      , 'trim|max_length[2]');
		$this->form_validation->set_rules('fak_log_audit'            , 'lang:fak_log_audit'            , 'trim|max_length[2]');
		$this->form_validation->set_rules('fak_singkatan'            , 'lang:fak_singkatan'            , 'trim|max_length[10]');
		$this->form_validation->set_rules('fak_nama_indonesia'       , 'lang:fak_nama_indonesia'       , 'trim|max_length[100]');
		$this->form_validation->set_rules('fak_nama_inggris'         , 'lang:fak_nama_inggris'         , 'trim|max_length[100]');
		$this->form_validation->set_rules('fak_dosen_kepala'         , 'lang:fak_dosen_kepala'         , 'trim|max_length[18]');
		$this->form_validation->set_rules('fak_tanggal_mulai_efektif', 'lang:fak_tanggal_mulai_efektif', 'trim|max_length[255]');
		$this->form_validation->set_rules('fak_tanggal_akhir_efektif', 'lang:fak_tanggal_akhir_efektif', 'trim|max_length[255]');
		$this->form_validation->set_rules('fak_deleted_at'           , 'lang:fak_deleted_at'           , 'valid_datetime');
		$this->form_validation->set_rules('fak_created_at'           , 'lang:fak_created_at'           , 'valid_datetime');
		$this->form_validation->set_rules('fak_updated_at'           , 'lang:fak_updated_at'           , 'valid_datetime');

		if ($this->form_validation->run())
		{
			// insert
			if($this->input->post('fak_id') == '')
			{
				$fak_id = $this->m_fakultas->insert(
					$this->input->post('fak_perguruan_tinggi'),
					$this->input->post('fak_status_validasi'),
					$this->input->post('fak_log_audit'),
					$this->input->post('fak_singkatan'),
					$this->input->post('fak_nama_indonesia'),
					$this->input->post('fak_nama_inggris'),
					$this->input->post('fak_dosen_kepala'),
					$this->input->post('fak_tanggal_mulai_efektif'),
					$this->input->post('fak_tanggal_akhir_efektif'),
					$this->input->post('fak_deleted_at'),
					$this->input->post('fak_created_at'),
					$this->input->post('fak_updated_at')
				);
				write_log('fakultas', 'insert', "PK = $fak_id");
				ajax_response();
			}
			// update
			else
			{
				$pk_id = $this->input->post('fak_id');
				//check if pk integer
				//$pk_id = uintval($pk_id);
				$this->m_fakultas->update(
					$pk_id,
					$this->input->post('fak_perguruan_tinggi'),
					$this->input->post('fak_status_validasi'),
					$this->input->post('fak_log_audit'),
					$this->input->post('fak_singkatan'),
					$this->input->post('fak_nama_indonesia'),
					$this->input->post('fak_nama_inggris'),
					$this->input->post('fak_dosen_kepala'),
					$this->input->post('fak_tanggal_mulai_efektif'),
					$this->input->post('fak_tanggal_akhir_efektif'),
					$this->input->post('fak_deleted_at'),
					$this->input->post('fak_created_at'),
					$this->input->post('fak_updated_at')
				);
				write_log('fakultas', 'update', "PK = $pk_id");
				ajax_response();
			}
		}
		else
		{ ajax_response('error', validation_errors()); }
	}

	/*
	 * delete method
     * generated by Doni's Framework Generator
	 *
	 * method handle delete from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function delete(){
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('delete');
		//$this->auth->validate();

		if($this->input->post('fak_id') === NULL) ajax_response();

		$all_deleted = array();
		foreach($this->input->post('fak_id') as $row){
			//$row = uintval($row);
			//permanent delete row, check MY_Model, you can set flag with ->update_single_column
			$this->m_fakultas->permanent_delete($row);

			//this is sample code if you cannot delete, but you must update status
			//$this->m_fakultas->update_single_column('fak_deleted', 1, $row);
			$all_deleted[] = $row;
		}
		write_log('fakultas', 'delete', 'PK = ' . implode(",", $all_deleted));

		ajax_response();
	}
}