<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Controller for handling jurusan module
 * @author : Doni Setio Pambudi (donisp06@gmail.com)
 */
class Jurusan extends CI_Controller {

	/*
	 * constructor class
	 */
	public function __construct() {
		parent::__construct();

		//set module, enable for authentication
		//$this->auth->set_default_module('jurusan');
		//enable dibawah ini jika divalidasi semua
		//$this->auth->validate(TRUE);
		//enable dibawah ini jika divalidasi user telah login saja
		//$this->auth->validate(TRUE, TRUE);

		//load this page model
		$this->load->model('m_jurusan');

		//load foregin lang if exist
		$this->lang->load('module/fakultas');

		//load lang, place this module after foreign lang, so module_ not overriden by foreign lang
		$this->lang->load('module/jurusan');
  	}

	/*
	 * method index controller jurusan
     * generated by Doni's Framework Generator
	 *
	 * this method act as module entry point
	 *
	 * @author: Doni Setio Pambudi
	 * @access: public
	 * @return: no return, view a page
	 */
	public function index(){
		//$this->auth->set_access('view');
		//$this->auth->validate(TRUE);

		//set informasi halaman
		$this->site_info->set_page_title($this->lang->line('module_title'), $this->lang->line('module_subtitle'));
		//set breadcrumb
		$this->site_info->add_breadcrumb($this->lang->line('module_title'));
		//add menu highlight
		$this->site_info->set_current_module('jurusan');

		//add masterpage script
		$this->asset_library->add_masterpage_script();
		//add page javascript
		$this->asset_library->add_js('js/pages/jurusan.js');

		$data = array();
		$this->load->model('m_fakultas');
		$data['fakultas'] = $this->m_fakultas->get(/*'fak_deleted = 0', 'fak_name asc'*/);

		//load view
		$this->load->view('base/header');
		$this->load->view('jurusan/master', $data);
		$this->load->view('base/footer');
	}

	/*
	 * get_datamaster method
     * generated by Doni's Framework Generator
	 *
	 * this method handle get datamaster request from datatables
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return	json string
	 */
	public function get_datamaster(){
		//only ajax is allowed
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('view');
		//$this->auth->validate();

		$filter_cols = array('jur_fakultas' => /*uintval(*/$this->input->post('jur_fakultas')/*, TRUE)*/);
		//$add_where = '';
		//set default where query
		$where = build_masterpage_filter($filter_cols /*, $add_where */);

		//get data
		$this->m_jurusan->get_datatable($where);
	}

	/*
	 * detail method
     * generated by Doni's Framework Generator
	 *
	 * this method handle get data detail from one primary key
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string
	 */
	public function detail(){
		//only ajax is allowed
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('view');
		//$this->auth->validate();

		//search data with pk for default
		$search_data = $this->input->post('jur_id');
		//if no search data exist, response error
		if($search_data === NULL)
			ajax_response('error');

		//activate if search data is integer
		//$search_data = uintval($search_data);

		//get detail
		$detail = $this->m_jurusan->get_by_column($search_data);

		//output return value
		if($detail !== NULL) ajax_response('ok', '', $detail);
		else ajax_response('error');
	}

	/*
	 * add method
     * generated by Doni's Framework Generator
	 *
	 * this method handle add data submit from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function add(){
		//$this->auth->set_access('add');
		//$this->auth->validate();

		//call save method
		$this->save();
	}

	/*
	 * edit method
     * generated by Doni's Framework Generator
	 *
	 * this method handle edit data submit from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function edit(){
		//$this->auth->set_access('edit');
		//$this->auth->validate();

		//call save method
		$this->save();
	}

	/*
	 * save method
     * generated by Doni's Framework Generator
	 *
	 * private method handle add and edit method
	 *
	 * @author	Doni Setio Pambudi
	 * @access	private
	 * @return		json string result ok or error
	 */
	private function save(){
		if(!$this->input->is_ajax_request()) show_404();

		//validation
		$this->load->library('form_validation');
		$this->form_validation->set_rules('jur_id'               , 'lang:jur_id'               , 'trim|max_length[3]');
		$this->form_validation->set_rules('jur_perguruan_tinggi' , 'lang:jur_perguruan_tinggi' , 'trim|max_length[6]');
		$this->form_validation->set_rules('jur_fakultas'         , 'lang:jur_fakultas'         , 'trim|max_length[3]');
		$this->form_validation->set_rules('jur_status_validasi'  , 'lang:jur_status_validasi'  , 'trim|max_length[2]');
		$this->form_validation->set_rules('jur_log_audit'        , 'lang:jur_log_audit'        , 'trim|max_length[2]');
		$this->form_validation->set_rules('jur_nama_indonesia'   , 'lang:jur_nama_indonesia'   , 'trim|max_length[100]');
		$this->form_validation->set_rules('jur_nama_inggris'     , 'lang:jur_nama_inggris'     , 'trim|max_length[100]');
		$this->form_validation->set_rules('jur_dosen_kepala'     , 'lang:jur_dosen_kepala'     , 'trim|max_length[18]');
		$this->form_validation->set_rules('jur_created_at'       , 'lang:jur_created_at'       , 'valid_datetime');
		$this->form_validation->set_rules('jur_updated_at'       , 'lang:jur_updated_at'       , 'valid_datetime');
		$this->form_validation->set_rules('jur_deleted_at'       , 'lang:jur_deleted_at'       , 'valid_datetime');
		$this->form_validation->set_rules('jur_periode_pelaporan', 'lang:jur_periode_pelaporan', 'trim|max_length[255]');

		if ($this->form_validation->run())
		{
			// insert
			if($this->input->post('jur_id') == '')
			{
				$jur_id = $this->m_jurusan->insert(
					$this->input->post('jur_perguruan_tinggi'),
					$this->input->post('jur_fakultas'),
					$this->input->post('jur_status_validasi'),
					$this->input->post('jur_log_audit'),
					$this->input->post('jur_nama_indonesia'),
					$this->input->post('jur_nama_inggris'),
					$this->input->post('jur_dosen_kepala'),
					$this->input->post('jur_created_at'),
					$this->input->post('jur_updated_at'),
					$this->input->post('jur_deleted_at'),
					$this->input->post('jur_periode_pelaporan')
				);
				write_log('jurusan', 'insert', "PK = $jur_id");
				ajax_response();
			}
			// update
			else
			{
				$pk_id = $this->input->post('jur_id');
				//check if pk integer
				//$pk_id = uintval($pk_id);
				$this->m_jurusan->update(
					$pk_id,
					$this->input->post('jur_perguruan_tinggi'),
					$this->input->post('jur_fakultas'),
					$this->input->post('jur_status_validasi'),
					$this->input->post('jur_log_audit'),
					$this->input->post('jur_nama_indonesia'),
					$this->input->post('jur_nama_inggris'),
					$this->input->post('jur_dosen_kepala'),
					$this->input->post('jur_created_at'),
					$this->input->post('jur_updated_at'),
					$this->input->post('jur_deleted_at'),
					$this->input->post('jur_periode_pelaporan')
				);
				write_log('jurusan', 'update', "PK = $pk_id");
				ajax_response();
			}
		}
		else
		{ ajax_response('error', validation_errors()); }
	}

	/*
	 * delete method
     * generated by Doni's Framework Generator
	 *
	 * method handle delete from master framework
	 *
	 * @author	Doni Setio Pambudi
	 * @access	public
	 * @return		json string result ok or error
	 */
	public function delete(){
		if(!$this->input->is_ajax_request()) show_404();

		//$this->auth->set_access('delete');
		//$this->auth->validate();

		if($this->input->post('jur_id') === NULL) ajax_response();

		$all_deleted = array();
		foreach($this->input->post('jur_id') as $row){
			//$row = uintval($row);
			//permanent delete row, check MY_Model, you can set flag with ->update_single_column
			$this->m_jurusan->permanent_delete($row);

			//this is sample code if you cannot delete, but you must update status
			//$this->m_jurusan->update_single_column('jur_deleted', 1, $row);
			$all_deleted[] = $row;
		}
		write_log('jurusan', 'delete', 'PK = ' . implode(",", $all_deleted));

		ajax_response();
	}
}